import{createClient}from'npm:@supabase/supabase-js@2';
const MAX_BODY=65536,allowedOrigins=()=>new Set((Deno.env.get('OPEN_FINANCE_ALLOWED_ORIGINS')||'').split(',').filter(Boolean));
export const correlationId=(request:Request)=>request.headers.get('x-correlation-id')||crypto.randomUUID();
export const corsHeaders=(request:Request)=>{const origin=request.headers.get('origin')||'';return allowedOrigins().has(origin)?{'access-control-allow-origin':origin,'access-control-allow-headers':'authorization,content-type,x-correlation-id','access-control-allow-methods':'GET,POST,OPTIONS','vary':'Origin'}:{}};
export const json=(request:Request,status:number,body:unknown,id:string)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','x-correlation-id':id,...corsHeaders(request)}});
export const readJson=async(request:Request)=>{const length=Number(request.headers.get('content-length')||0);if(length>MAX_BODY)throw Object.assign(new Error('Body excessivo.'),{status:413,code:'BODY_TOO_LARGE'});const text=await request.text();if(text.length>MAX_BODY)throw Object.assign(new Error('Body excessivo.'),{status:413,code:'BODY_TOO_LARGE'});try{return text?JSON.parse(text):{}}catch{throw Object.assign(new Error('JSON inválido.'),{status:400,code:'INVALID_BODY'})}};
export const authenticate=async(request:Request)=>{const authorization=request.headers.get('authorization');if(!authorization?.startsWith('Bearer '))throw Object.assign(new Error('Não autorizado.'),{status:401,code:'UNAUTHORIZED'});const client=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:authorization}}}),{data,error}=await client.auth.getUser();if(error||!data.user)throw Object.assign(new Error('Não autorizado.'),{status:401,code:'UNAUTHORIZED'});return{user:data.user,client}};
export const adminClient=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
export const secureHandler=(methods:string[],handler:(context:any)=>Promise<Response>,options:{webhook?:boolean}={})=>Deno.serve(async(request)=>{const id=correlationId(request);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(request)});if(!methods.includes(request.method))return json(request,405,{error:{code:'METHOD_NOT_ALLOWED',message:'Método não permitido.'}},id);try{const auth=options.webhook?null:await authenticate(request),body=request.method==='POST'?await readJson(request):{};return await handler({request,id,body,auth,admin:adminClient()})}catch(error:any){return json(request,error.status||500,{error:{code:error.code||'OPEN_FINANCE_ERROR',message:error.status&&error.status<500?error.message:'Operação indisponível.'}},id)}});
