import {mapConsent,mapExternalAccount,mapInstitution} from '../../domain/openFinance/canonicalMapper.js';import {OpenFinanceError} from '../../domain/openFinance/errors.js'
const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString()
export class MockOpenFinanceProvider{
  #scenario;#consents=new Map();#sessions=new Map();#webhooks=new Set()
  constructor({scenario='success'}={}){this.#scenario=scenario}
  getProviderInfo(){return{name:'mock',environment:'sandbox',contractVersion:'open-finance-canonical-v1',networkRequired:false}}
  async #guard(){if(this.#scenario==='timeout')throw new OpenFinanceError('PROVIDER_TIMEOUT','O provedor excedeu o tempo limite.',{retryable:true});if(this.#scenario==='rate_limit')throw new OpenFinanceError('PROVIDER_RATE_LIMITED','Limite temporário do provedor.',{retryable:true,retryAfterSeconds:30})}
  async createConnectionSession(input){await this.#guard();const sessionId=id(),consentId=id(),createdAt=now(),state=input.state;this.#consents.set(consentId,{id:consentId,status:'awaiting_user',scopes:input.scopes||['accounts'],createdAt,expiresAt:new Date(Date.now()+86400000).toISOString()});const session={sessionId,provider:'mock',providerConsentId:consentId,state,expiresAt:new Date(Date.now()+600000).toISOString(),widgetToken:`mock_session_${sessionId}`,widgetUrl:`https://sandbox.invalid/connect/${sessionId}`};this.#sessions.set(sessionId,session);return session}
  async exchangeCallback(input){await this.#guard();if(input.error||!input.state||!input.sessionId||!this.#sessions.has(input.sessionId))throw new OpenFinanceError('CALLBACK_INVALID','Callback inválido.');const session=this.#sessions.get(input.sessionId),consent=this.#consents.get(session.providerConsentId);if(this.#scenario==='rejected'){consent.status='rejected';return{status:'rejected',providerConnectionId:null,consent:mapConsent(consent,'mock')}}consent.status=this.#scenario==='expired'?'expired':'active';consent.authorizedAt=now();return{status:consent.status,providerConnectionId:`mock_connection_${input.sessionId}`,consent:mapConsent(consent,'mock')}}
  async listInstitutions(){await this.#guard();const extra=this.#scenario==='unknown_field'?{futureCapability:'new'}:{};return[{id:'mock-bank-1',name:'Banco Sandbox',displayName:'Banco Sandbox',brandName:'Sandbox',country:'BR',institutionType:'bank',supportedProducts:['accounts','credit_cards'],supportedAccountTypes:['checking','credit_card'],status:'active',schemaVersion:'mock-v1',...extra},{id:'mock-bank-2',name:'Cooperativa Sandbox',status:'active'}].map((item)=>mapInstitution(item,'mock'))}
  async getConsent(providerConsentId){const value=this.#consents.get(providerConsentId);if(!value)throw new OpenFinanceError('CONNECTION_NOT_FOUND','Consentimento não encontrado.');return mapConsent(value,'mock')}
  async renewConsent(providerConsentId){const value=this.#consents.get(providerConsentId);if(!value)throw new OpenFinanceError('CONNECTION_NOT_FOUND','Consentimento não encontrado.');if(value.status==='revoked')throw new OpenFinanceError('CONSENT_REVOKED','Consentimento revogado.');value.status='active';value.expiresAt=new Date(Date.now()+86400000).toISOString();return mapConsent(value,'mock')}
  async revokeConsent(providerConsentId){const value=this.#consents.get(providerConsentId);if(!value||value.status==='revoked')return;value.status='revoked';value.revokedAt=now()}
  async listAccounts(connection){await this.#guard();const base=[{id:'account-1',type:'checking',name:'Conta principal',currency:'BRL',maskedNumber:'****1234',branchCode:'0001',status:'active',accountFingerprint:'mock:account-1'},{id:'card-1',type:'credit_card',name:'Cartão',currency:'BRL',maskedNumber:'****9876',status:'active',accountFingerprint:'mock:card-1'}];if(this.#scenario==='removed_account')base[0].status='removed';if(this.#scenario==='partial')base[0]={id:'account-1',name:'Conta parcial',partial:true,status:'active'};return base.map((item)=>mapExternalAccount(item,{provider:'mock',connectionId:connection.id,institutionId:connection.institutionId}))}
  async getConnectionStatus(connection){return{provider:'mock',providerConnectionId:connection.providerConnectionId,status:this.#scenario==='expired'?'expired':'active',checkedAt:now()}}
  async validateWebhook(request){if(!request.signature||request.signature!=='mock-valid')throw new OpenFinanceError('PROVIDER_UNAUTHORIZED','Webhook inválido.');if(!request.eventId)throw new OpenFinanceError('PARTIAL_RESPONSE','Evento sem identificador.');const duplicate=this.#webhooks.has(request.eventId);this.#webhooks.add(request.eventId);return{provider:'mock',providerEventId:request.eventId,eventType:request.eventType||'unknown',connectionReference:request.connectionId,idempotencyKey:`mock:${request.eventId}`,duplicate,payloadSummary:{keys:Object.keys(request.payload||{}).filter((key)=>!/(token|secret)/i.test(key)).slice(0,20)}}}
  async healthCheck(){return{provider:'mock',status:this.#scenario==='unavailable'?'unavailable':'healthy',checkedAt:now()}}
}
