import test from 'node:test';import assert from 'node:assert/strict';import { classifyFinancialEvent } from '../src/domain/financialEvents/classifier.js';import { calculateInvoiceSettlement } from '../src/domain/financialEvents/invoiceSettlementService.js';import { calculateInternalTransferEffects } from '../src/domain/financialEvents/transferService.js';import { validateReversal } from '../src/domain/financialEvents/reversalService.js';import { createFinancialEventLink,revertFinancialEventLink } from '../src/domain/financialEvents/linkService.js';import { selectInstallmentsForCompetence } from '../src/domain/financialEvents/installmentService.js'
const userId='u1',input=(patch={})=>({id:crypto.randomUUID(),userId,amount:'100.00',date:'2026-08-05',type:'expense',...patch})
test('pagamento parcial e atrasado separam principal, juros e tarifa',()=>{const partial=calculateInvoiceSettlement({invoiceAmount:'500.00',paymentAmount:'200.00'});assert.equal(partial.status,'partially_settled');assert.equal(partial.remainingMinor,'30000');assert.equal(partial.createsExpenseMinor,'0');const late=calculateInvoiceSettlement({invoiceAmount:'500.00',paymentAmount:'530.00',interest:'20.00',fees:'10.00'});assert.equal(late.status,'settled');assert.equal(late.principalMinor,'50000');assert.equal(late.createsExpenseMinor,'3000')})
test('transferência própria é neutra e tarifa é despesa separada',()=>{const effects=calculateInternalTransferEffects({amount:'100.00',fee:'2.00'});assert.equal(effects.sourceCashMinor,'-10200');assert.equal(effects.destinationCashMinor,'10000');assert.equal(effects.principalNetWorthMinor,'0');assert.equal(effects.resultMinor,'-200')})
test('saque, depósito e transferência externa ambíguos exigem revisão',()=>{for(const item of [input({description:'Saque ATM'}),input({description:'Depósito salário',type:'income'}),input({manualEventType:'external_transfer_out'})])assert.equal(classifyFinancialEvent({input:item}).requiresReview,true)})
test('estorno total e parcial preservam compra e não excedem elegível',()=>{assert.deepEqual(validateReversal({originalAmount:'100.00',reversalAmount:'40.00'}),{valid:true,partial:true,eligibleAfterMinor:'6000'});assert.equal(validateReversal({originalAmount:'100.00',alreadyReversed:'80.00',reversalAmount:'30.00'}).valid,false);const event=classifyFinancialEvent({input:input({type:'income',originalEventId:'purchase-1',description:'Estorno'})});assert.equal(event.eventType,'refund');assert.notEqual(event.eventType,'cash_income')})
test('chargeback mantém vínculo reversível e idempotente',()=>{const first=createFinancialEventLink({userId,sourceEventId:'cb',targetEventId:'purchase',linkType:'chargeback_of'}),again=createFinancialEventLink({userId,sourceEventId:'cb',targetEventId:'purchase',linkType:'chargeback_of',existingLinks:[first.link]});assert.equal(again.created,false);const reverted=revertFinancialEventLink({link:first.link,revertedBy:'user',reason:'chargeback cancelado'});assert.equal(reverted.changed,true);assert.equal(revertFinancialEventLink({link:reverted.link,revertedBy:'user',reason:'retry'}).changed,false)})
test('parcela futura não entra na competência atual',()=>{const events=[{id:'aug',competenceDate:'2026-08-01'},{id:'sep',competenceDate:'2026-09-01'}];assert.deepEqual(selectInstallmentsForCompetence(events,'2026-08').map((item)=>item.id),['aug']);const classified=classifyFinancialEvent({input:input({cardId:'c',installmentNumber:2,installmentGroupId:'g',competenceDate:'2026-09-01'}),referenceDate:'2026-08-01'});assert.equal(classified.eventType,'under_review');assert.ok(classified.warnings.includes('FUTURE_INSTALLMENT_EXCLUDED_FROM_CURRENT_PERIOD'))})
test('compra de investimento não vira consumo',()=>{const event=classifyFinancialEvent({input:input({manualEventType:'investment_purchase',type:null})});assert.equal(event.effects.consumption,'0');assert.equal(event.effects.cash,'-10000')})
