import test from 'node:test'
import assert from 'node:assert/strict'
import { appendInvoicePayment, evaluateInvoiceConsistency, reopenInvoiceRecord } from '../src/utils/invoiceReconciliation.js'
import { archiveInvoice, isOrphanInvoice, restoreInvoice } from '../src/utils/orphanInvoices.js'
import { analyzeInstallmentIdentity, migrateSafeInstallmentIdentities } from '../src/utils/identity.js'
import { analyzeDuplicates, removeConfirmedDuplicate } from '../src/utils/deduplication.js'
import { createRemainingCardInstallments, isDuplicateInstallment } from '../src/utils/invoiceCalculations.js'
import { calculateInvoiceStatus } from '../src/utils/invoiceCalculations.js'
import { distributePurchaseTotal, getTransactionAmount, migrateSafeInstallmentValues, normalizeInstallmentValues } from '../src/utils/installmentValueCalculations.js'
import { applyTemporalAssignment } from '../src/utils/temporalAssignments.js'
import { addMonthsSafe, compareFinancialDates, formatLocalDate } from '../src/utils/dateCalculations.js'
import { createOfficialInvoiceRecord, migrateSafeInvoiceDates } from '../src/utils/invoiceDates.js'
import { addCardBillingConfiguration, getCardBillingConfigForCompetence, migrateLegacyCardConfigurations, validateBillingConfigurations } from '../src/utils/cardBillingConfig.js'
import { getFutureCommittedExpenses, getMonthlyFinancialSummary, getNextThirtyDaysSummary, getOpenInvoiceTotal, getProjectedBalance, getRealizedExpenses, getRealizedIncome, isTransactionOverdue } from '../src/utils/financialSelectors.js'
import { filterByChartScope, getMonthlyChartSeries, groupTransactionsForChart } from '../src/utils/chartSelectors.js'
import { buildMonthlyForecast } from '../src/utils/forecastCalculations.js'
import { clearFilter, defaultFilters, filterTransactions, getActiveFilterCount, matchTransactionSearch } from '../src/utils/filtering.js'
import { applySafeBulkUpdate, getDeletionTargets, summarizeTransactions } from '../src/utils/transactionOperations.js'

const paid = { id: 'old', invoiceId: 'card-2026-08', amount: 500, status: 'paid' }
const pending = { id: 'new', invoiceId: 'card-2026-08', amount: 100, status: 'pending' }
const invoice = { id: 'card-2026-08', status: 'paid', paidAt: '2026-08-01T12:00:00.000Z', total: 600, totalPaid: 500, totalPending: 100, transactions: [paid, pending], paymentHistory: [{ paidAt: '2026-08-01T12:00:00.000Z', amount: 500 }] }
test('fase 6: identifica fatura paga com compra pendente e separa saldo', () => { const result = evaluateInvoiceConsistency(invoice, [paid, pending]); assert.equal(result.consistent, false); assert.equal(result.totalPaid, 500); assert.equal(result.totalPending, 100); assert.ok(result.issues.includes('PAID_INVOICE_WITH_PENDING_TRANSACTIONS')) })
test('fase 6: reabertura preserva pagamento e registra auditoria', () => { const record = reopenInvoiceRecord({ id: invoice.id, status: 'paid', paidAt: invoice.paidAt, paymentHistory: invoice.paymentHistory }, invoice, pending.id, '2026-08-02T12:00:00.000Z'); assert.equal(record.paymentHistory[0].amount, 500); assert.equal(record.reopenHistory.length, 1); assert.equal(record.status, null) })
test('fase 6: pagamento posterior registra somente saldo pendente', () => { const record = appendInvoicePayment({ id: invoice.id, paymentHistory: invoice.paymentHistory }, invoice, '2026-08-03T12:00:00.000Z'); assert.equal(record.paymentHistory.length, 2); assert.equal(record.paymentHistory[1].amount, 100); assert.equal(record.status, 'paid') })
test('fase 6: paidAt histórico não mantém fatura reaberta como paga', () => { assert.notEqual(calculateInvoiceStatus({ paidAt: invoice.paidAt, reopenedAt: '2026-08-02', status: null, closingDate: '2026-08-30', dueDate: '2026-09-03' }, new Date(2026, 7, 10)), 'paid') })
test('fase 7: diferencia órfã descartável de registro histórico', () => { assert.equal(isOrphanInvoice({ id: 'card-2026-09' }, [], [{ id: 'card' }]).disposable, true); const historical = isOrphanInvoice({ id: 'card-2026-09', paidAt: '2026-09-01' }, [], [{ id: 'card' }]); assert.equal(historical.orphan, true); assert.equal(historical.disposable, false) })
test('fase 7: arquivamento separa identidade histórica e é reversível', () => { const source = { id: 'card-2026-09', paymentHistory: [{ amount: 10 }] }; const archived = archiveInvoice(source, 'empty-orphan-invoice', '2026-09-02T00:00:00Z'); assert.equal(archived.archived, true); assert.notEqual(archived.id, source.id); assert.deepEqual(archived.paymentHistory, source.paymentHistory); const restored = restoreInvoice(archived); assert.equal(restored.archived, false); assert.equal(restored.id, source.id) })
test('fase 8: migra apenas identidade segura sem alterar dados financeiros', () => { const source = [{ id: 'a', purchaseGroupId: 'p', installmentNumber: 1, installmentTotal: 2, amount: 50, invoiceMonth: 8, status: 'paid' }, { id: 'b', purchaseGroupId: 'p', installmentNumber: 2, installmentTotal: 2, amount: 50, invoiceMonth: 9, status: 'pending' }]; const result = migrateSafeInstallmentIdentities(source); assert.equal(result.transactions[0].installmentGroupId, result.transactions[1].installmentGroupId); assert.deepEqual(result.transactions.map(({ amount, invoiceMonth, status }) => ({ amount, invoiceMonth, status })), source.map(({ amount, invoiceMonth, status }) => ({ amount, invoiceMonth, status }))); assert.equal(result.report.beforeCount, result.report.afterCount) })
test('fase 8: caso sem evidência permanece ambíguo e intocado', () => { const source = [{ id: 'a', installmentNumber: 1, installmentTotal: 2, amount: 10 }]; assert.equal(analyzeInstallmentIdentity(source).ambiguous.length, 1); assert.equal(migrateSafeInstallmentIdentities(source).transactions[0].installmentGroupId, undefined) })
test('fase 9: compras iguais com IDs diferentes são prováveis, não confirmadas', () => { const items = [{ id: 'a', description: 'Café', amount: 10, date: '2026-01-01' }, { id: 'b', description: 'Café', amount: 10, date: '2026-01-01' }]; const report = analyzeDuplicates(items); assert.equal(report.confirmed.length, 0); assert.equal(report.probable.length, 1); assert.equal(items.length, 2) })
test('fase 9: operationId repetida é confirmada e corrigível explicitamente', () => { const items = [{ id: 'a', operationId: 'op', description: 'A' }, { id: 'b', operationId: 'op', description: 'A' }]; assert.equal(analyzeDuplicates(items).confirmed[0].reason, 'same-operation-id'); assert.deepEqual(removeConfirmedDuplicate(items, 'b', 'a').map((item) => item.id), ['a']) })
test('fase 9: parcelamentos iguais independentes não se bloqueiam', () => { const cardData = { id: 'card', name: 'Card', closingDay: 25, dueDay: 3 }; const base = { description: 'Compra', amount: 100, date: '2026-07-01', installmentTotal: 2, installmentNumber: 1, invoiceMonth: 8, invoiceYear: 2026 }; const first = createRemainingCardInstallments(base, cardData); const second = createRemainingCardInstallments(base, cardData); assert.notEqual(first[0].installmentGroupId, second[0].installmentGroupId); assert.equal(isDuplicateInstallment(second[0], first), false); assert.equal(isDuplicateInstallment(first[0], first), true) })
test('fase 10: divisão monetária distribui centavos exatamente', () => { const values = distributePurchaseTotal(100, 3); assert.deepEqual(values, [33.34, 33.33, 33.33]); assert.equal(values.reduce((sum, value) => sum + value, 0), 100) })
test('fase 10: normalização sincroniza amount e installmentAmount', () => { const value = normalizeInstallmentValues({ amount: 100, installmentNumber: 2, installmentTotal: 3 }); assert.equal(value.amount, 100); assert.equal(value.installmentAmount, 100); assert.equal(value.valueInputMode, 'installment'); assert.equal(getTransactionAmount(value), 100) })
test('fase 10: migração segura preserva contagem e campos financeiros', () => { const source = [{ id: 'a', amount: 10, installmentNumber: 1, installmentTotal: 2, invoiceId: 'x', status: 'paid' }]; const result = migrateSafeInstallmentValues(source); assert.equal(result.report.beforeCount, result.report.afterCount); assert.equal(result.transactions[0].installmentAmount, 10); assert.equal(result.transactions[0].invoiceId, 'x'); assert.equal(result.transactions[0].status, 'paid') })
test('fase 11: datas financeiras permanecem locais e atravessam o ano', () => { assert.equal(formatLocalDate('2026-02-03'), '2026-02-03'); assert.equal(addMonthsSafe('2026-12-31', 1), '2027-01-31'); assert.equal(compareFinancialDates('2026-01-01', '2026-01-02'), -1) })
test('fase 11: manter fatura transforma atribuição em manual', () => { const source = [{ id: 'a', cardId: 'card', date: '2026-01-01', invoiceId: 'card-2026-02', invoiceMonth: 2, invoiceYear: 2026, invoiceAssignmentMode: 'automatic', installmentNumber: 1, installmentTotal: 1, status: 'pending' }]; const result = applyTemporalAssignment(source, 'a', { date: '2026-01-20' }, { id: 'card', closingDay: 25, dueDay: 3 }, { mode: 'keep' }); assert.equal(result.transactions[0].invoiceId, source[0].invoiceId); assert.equal(result.transactions[0].invoiceAssignmentMode, 'manual'); assert.equal(result.transactions[0].dateAssignmentOverride, true) })
test('fase 11: esta e próximas preserva sequência mensal e parcelas anteriores', () => { const source = [1, 2, 3].map((number) => ({ id: String(number), cardId: 'card', date: '2026-10-01', invoiceId: `old-${number}`, invoiceMonth: 9 + number, invoiceYear: 2026, invoiceAssignmentMode: 'automatic', installmentGroupId: 'g', installmentNumber: number, installmentTotal: 3, status: 'pending' })); const result = applyTemporalAssignment(source, '2', { date: '2026-11-01' }, { id: 'card', closingDay: 25, dueDay: 3 }, { mode: 'recalculate', scope: 'future' }); assert.equal(result.transactions[0].invoiceId, 'old-1'); assert.equal(result.transactions[1].invoiceMonth, 12); assert.equal(result.transactions[2].invoiceMonth, 1); assert.equal(result.transactions[2].invoiceYear, 2027) })
test('fase 12: registro oficial preserva data histórica', () => { const transaction = { invoiceId: 'card-2026-08', cardId: 'card', invoiceMonth: 8, invoiceYear: 2026, dueDate: '2026-08-05' }; const record = createOfficialInvoiceRecord(transaction, { id: 'card', closingDay: 25, dueDay: 3 }, {}, 'historical'); assert.equal(record.dueDate, '2026-08-05'); assert.equal(record.dateSource, 'historical'); assert.equal(record.invoiceId, transaction.invoiceId) })
test('fase 12: migração consolida somente datas históricas unívocas', () => { const transactions = [{ id: 'a', invoiceId: 'card-2026-08', cardId: 'card', invoiceMonth: 8, invoiceYear: 2026, dueDate: '2026-08-05' }, { id: 'b', invoiceId: 'card-2026-09', cardId: 'card', invoiceMonth: 9, invoiceYear: 2026, dueDate: '2026-09-03' }, { id: 'c', invoiceId: 'card-2026-09', cardId: 'card', invoiceMonth: 9, invoiceYear: 2026, dueDate: '2026-09-04' }]; const result = migrateSafeInvoiceDates(transactions, [], [{ id: 'card', closingDay: 25, dueDay: 3 }]); assert.deepEqual(result.report.created, ['card-2026-08']); assert.equal(result.report.ambiguous.length, 1) })
test('fase 13: migração cria vigência inicial sem alterar cartão legado', () => { const source = [{ id: 'card', closingDay: 25, dueDay: 3 }]; const result = migrateLegacyCardConfigurations(source); assert.equal(result.cards.length, source.length); assert.equal(result.cards[0].closingDay, 25); assert.equal(result.cards[0].billingConfigurations[0].source, 'legacy-migrated') })
test('fase 13: nova vigência encerra anterior e seleciona regra por competência', () => { const migrated = migrateLegacyCardConfigurations([{ id: 'card', closingDay: 25, dueDay: 3 }]).cards[0]; const card = addCardBillingConfiguration(migrated, { closingDay: 20, dueDay: 28, effectiveFrom: '2026-09' }, '2026-08-01T00:00:00Z'); assert.equal(getCardBillingConfigForCompetence(card, 8, 2026).config.closingDay, 25); assert.equal(getCardBillingConfigForCompetence(card, 9, 2026).config.closingDay, 20); assert.equal(card.billingConfigurations[0].effectiveTo, '2026-08'); assert.equal(validateBillingConfigurations(card.billingConfigurations).valid, true) })
test('fase 13: sobreposição e vigência inválida são rejeitadas', () => { const invalid = [{ configId: 'a', effectiveFrom: '2026-01', effectiveTo: null }, { configId: 'b', effectiveFrom: '2026-09', effectiveTo: null }]; assert.equal(validateBillingConfigurations(invalid).valid, false); assert.throws(() => addCardBillingConfiguration({ billingConfigurations: [] }, { closingDay: 20, dueDay: 28, effectiveFrom: 'invalida' })) })
test('fase 14: separa realizado, pendente, vencido e futuro sem dupla contagem', () => { const items = [{ id: 'r', type: 'income', amount: 1000, status: 'paid', competenceMonth: 7, competenceYear: 2026 }, { id: 'p', type: 'expense', amount: 200, status: 'paid', competenceMonth: 7, competenceYear: 2026 }, { id: 'o', type: 'expense', amount: 50, status: 'pending', dueDate: '2026-07-01', competenceMonth: 7, competenceYear: 2026 }, { id: 'f', type: 'expense', amount: 100, status: 'pending', dueDate: '2026-09-03', invoiceMonth: 9, invoiceYear: 2026, cardId: 'card' }]; const reference = new Date(2026, 6, 15); assert.equal(getRealizedIncome(items), 1000); assert.equal(getRealizedExpenses(items), 200); assert.equal(isTransactionOverdue(items[2], reference), true); assert.equal(getFutureCommittedExpenses(items, reference), 100); assert.equal(getProjectedBalance(items), 650) })
test('fase 14: fatura reaberta usa somente saldo pendente', () => { assert.equal(getOpenInvoiceTotal([{ status: 'open', total: 600, totalPaid: 500, totalPending: 100 }]), 100) })
test('fase 14: competência e próximos 30 dias são determinísticos', () => { const items = [{ id: 'a', type: 'expense', amount: 10, status: 'pending', dueDate: '2026-12-20', competenceMonth: 12, competenceYear: 2026 }, { id: 'b', type: 'expense', amount: 20, status: 'pending', dueDate: '2027-01-10', competenceMonth: 1, competenceYear: 2027 }]; assert.equal(getMonthlyFinancialSummary(items, [], 12, 2026, new Date(2026, 11, 1)).expensesForecast, 10); assert.equal(getNextThirtyDaysSummary(items, [], new Date(2026, 11, 15)).expenses, 30) })
test('fase 15: alterna realizado, previsto e combinado sem alterar dados', () => { const items = [{ id: 'a', type: 'expense', category: 'Casa', amount: 10, status: 'paid' }, { id: 'b', type: 'expense', category: 'Casa', amount: 20, status: 'pending' }]; const before = JSON.stringify(items); assert.equal(filterByChartScope(items, 'realized').length, 1); assert.equal(filterByChartScope(items, 'forecast').length, 1); assert.equal(groupTransactionsForChart(items, 'category', 'all').Casa.value, 30); assert.equal(JSON.stringify(items), before) })
test('fase 15: série mensal usa competência e trata virada de ano', () => { const items = [{ id: 'a', type: 'expense', amount: 10, status: 'paid', invoiceMonth: 12, invoiceYear: 2026, cardId: 'card' }, { id: 'b', type: 'expense', amount: 20, status: 'pending', invoiceMonth: 1, invoiceYear: 2027, cardId: 'card' }]; const series = getMonthlyChartSeries(items, 2, new Date(2027, 0, 15)); assert.equal(series[0].expensesRealized, 10); assert.equal(series[1].expensesForecast, 20) })
test('fase 16: previsão mantém meses vazios e atravessa o ano', () => { const forecast = buildMonthlyForecast([], [], 3, new Date(2026, 11, 10)); assert.deepEqual(forecast.map((item) => [item.month, item.year]), [[12, 2026], [1, 2027], [2, 2027]]); assert.ok(forecast.every((item) => item.monthlyBalance === 0)) })
test('fase 16: saldo acumulado combina realizado e previsto uma vez', () => { const items = [{ id: 'a', type: 'income', amount: 1000, status: 'paid', competenceMonth: 7, competenceYear: 2026 }, { id: 'b', type: 'expense', amount: 200, status: 'paid', competenceMonth: 7, competenceYear: 2026 }, { id: 'c', type: 'expense', amount: 100, status: 'pending', invoiceMonth: 8, invoiceYear: 2026, cardId: 'card', installmentTotal: 2 }]; const forecast = buildMonthlyForecast(items, [], 3, new Date(2026, 6, 1)); assert.equal(forecast[0].monthlyBalance, 800); assert.equal(forecast[1].monthlyBalance, -100); assert.equal(forecast[1].accumulatedBalance, 700); assert.equal(forecast[1].futureInstallments, 1) })
test('fase 16: fatura reaberta é informativa e não duplica despesas', () => { const items = [{ id: 'a', type: 'expense', amount: 100, status: 'pending', invoiceMonth: 7, invoiceYear: 2026, cardId: 'card' }]; const invoices = [{ id: 'card-2026-07', invoiceMonth: 7, invoiceYear: 2026, status: 'open', total: 600, totalPaid: 500, totalPending: 100 }]; const month = buildMonthlyForecast(items, invoices, 3, new Date(2026, 6, 1))[0]; assert.equal(month.expensesForecast, 100); assert.equal(month.invoiceTotal, 100); assert.equal(month.monthlyBalance, -100) })
test('fase 17: busca normalizada encontra descrição e cartão sem acentos', () => { const item = { description: 'Café da manhã', cardId: 'card', status: 'pending' }; assert.equal(matchTransactionSearch(item, ' cafe ', { cards: [{ id: 'card', name: 'Cartão Ágil' }] }), true); assert.equal(matchTransactionSearch(item, 'cartao agil', { cards: [{ id: 'card', name: 'Cartão Ágil' }] }), true) })
test('fase 17: filtros combinados usam AND e preservam dados', () => { const items = [{ id: 'a', description: 'Mercado', type: 'expense', amount: 90, category: 'Casa', costCenter: 'Pessoal', status: 'pending', dueDate: '2026-08-10', competenceMonth: 8, competenceYear: 2026 }, { id: 'b', description: 'Mercado', type: 'expense', amount: 600, category: 'Casa', costCenter: 'Pessoal', status: 'pending', dueDate: '2026-08-10', competenceMonth: 8, competenceYear: 2026 }]; const before = JSON.stringify(items); const result = filterTransactions(items, { ...defaultFilters, category: 'Casa', costCenter: 'Pessoal', status: 'pending', competenceMonth: 8, competenceYear: 2026, dateFrom: '2026-08-01', dateTo: '2026-08-31', minAmount: 50, maxAmount: 500 }); assert.deepEqual(result.map((item) => item.id), ['a']); assert.equal(JSON.stringify(items), before) })
test('fase 17: ordenação, contagem e remoção individual são consistentes', () => { const items = [{ id: 'a', description: 'B', amount: 20, date: '2026-01-01' }, { id: 'b', description: 'A', amount: 10, date: '2026-02-01' }]; assert.deepEqual(filterTransactions(items, { ...defaultFilters, sort: 'description' }).map((item) => item.id), ['b', 'a']); const filters = { ...defaultFilters, search: 'a', overdueOnly: true }; assert.equal(getActiveFilterCount(filters), 2); assert.equal(clearFilter(filters, 'search').search, ''); assert.equal(clearFilter(filters, 'overdueOnly').overdueOnly, false) })
test('fase 18: exclusão respeita parcela atual, futuras e grupo sem cruzar identidades', () => { const items = [{ id: 'a', installmentGroupId: 'g', installmentNumber: 1 }, { id: 'b', installmentGroupId: 'g', installmentNumber: 2 }, { id: 'c', installmentGroupId: 'g', installmentNumber: 3 }, { id: 'x', installmentGroupId: 'other', installmentNumber: 3 }]; assert.deepEqual(getDeletionTargets(items, 'b', 'single').map((item) => item.id), ['b']); assert.deepEqual(getDeletionTargets(items, 'b', 'future').map((item) => item.id), ['b', 'c']); assert.deepEqual(getDeletionTargets(items, 'b', 'group').map((item) => item.id), ['a', 'b', 'c']) })
test('fase 18: edição em lote aceita somente campos seguros', () => { const items = [{ id: 'a', amount: 10, installmentGroupId: 'g', status: 'pending' }, { id: 'b', amount: 20 }]; const result = applySafeBulkUpdate(items, ['a'], { category: 'Casa', amount: 999, installmentGroupId: 'bad' }); assert.equal(result[0].category, 'Casa'); assert.equal(result[0].amount, 10); assert.equal(result[0].installmentGroupId, 'g'); assert.equal(result[1], items[1]) })
test('fase 18: resumo informa impacto pago, faturas e parcelamentos', () => { const items = [{ id: 'a', amount: 10, status: 'paid', invoiceId: 'i', installmentGroupId: 'g' }, { id: 'b', amount: 20, status: 'pending', invoiceId: 'i', installmentGroupId: 'g' }]; const summary = summarizeTransactions(items, [{ id: 'i', status: 'paid' }], new Date(2026, 0, 1)); assert.equal(summary.count, 2); assert.equal(summary.total, 30); assert.equal(summary.paid, 2); assert.equal(summary.invoices, 1); assert.equal(summary.installmentGroups, 1) })
