const fail = (error, action) => { if (error) throw new Error(`${action}: ${error.message}`, { cause: error }) }
const row = (event, runId) => ({ id:event.id,user_id:event.userId,classification_run_id:runId,financial_transaction_id:event.financialTransactionId,raw_transaction_id:event.rawTransactionId,event_type:event.eventType,subtype:event.subtype,classification_status:event.classificationStatus,classification_method:event.classificationMethod,classification_version:event.classificationVersion,matrix_version:'accounting-matrix-v1',confidence:event.confidence,reasons:event.reasons,warnings:event.warnings,effects:event.effects,account_id:event.accountId,card_id:event.cardId,invoice_id:event.invoiceId,transfer_id:event.transferId,installment_group_id:event.installmentGroupId,occurred_at:event.dates?.occurredAt,accounting_date:event.dates?.accountingDate,competence_date:event.dates?.competenceDate,settled_at:event.dates?.settledAt,invoice_date:event.dates?.invoiceDate,projection_date:event.dates?.projectionDate,idempotency_key:event.idempotencyKey,metadata:{requiresLink:event.requiresLink,proposedEventType:event.proposedEventType}})
export const createFinancialEventRepository = (client) => ({
  async saveRun(run) { const {data,error}=await client.from('classification_runs').upsert(run).select('*').single(); fail(error,'Salvar execução de classificação'); return data },
  async saveEvents(events,runId) { const writable=events.filter((item)=>!item.confirmedAt);if(!writable.length)return[]; const {data,error}=await client.from('financial_events').upsert(writable.map((item)=>row(item,runId)),{onConflict:'user_id,idempotency_key',ignoreDuplicates:false}).select('*'); fail(error,'Salvar eventos sombra'); return data },
  async listEvents({userId,from,to,limit=1000}) { let query=client.from('financial_events').select('*').eq('user_id',userId).is('superseded_at',null).limit(limit); if(from)query=query.gte('accounting_date',from); if(to)query=query.lte('accounting_date',to); const {data,error}=await query; fail(error,'Listar eventos sombra'); return data||[] },
  async saveComparisons(rows) { if(!rows.length)return[]; const {data,error}=await client.from('financial_classification_comparisons').insert(rows).select('*'); fail(error,'Salvar comparações'); return data },
  async appendClassificationAudit(events,runId) { if(!events.length)return[];const rows=events.map((event)=>({id:crypto.randomUUID(),user_id:event.userId,entity_type:'financial_event',entity_id:event.id,event_type:'financial_event_classified',actor_type:'system',source:'system',correlation_id:runId,after_data:{eventType:event.eventType,status:event.classificationStatus,effects:event.effects},changed_fields:['classification'],reason:event.reasons.join(','),metadata:{classificationVersion:event.classificationVersion,warnings:event.warnings},idempotency_key:`financial-event:${event.id}:${event.classificationVersion}`,occurred_at:new Date().toISOString()}));const {data,error}=await client.from('audit_events').upsert(rows,{onConflict:'user_id,idempotency_key',ignoreDuplicates:true}).select('*');fail(error,'Registrar auditoria da classificação');return data},
})
