const fail = (error, action) => { if (error) throw new Error(`${action}: ${error.message}`, { cause: error }) }
const batchRow = (batch) => ({ id: batch.id, user_id: batch.userId, file_type: batch.fileType, original_filename: batch.originalFilename, file_size: batch.fileSize, file_hash: batch.fileHash, parser_version: batch.parserVersion, status: batch.status, financial_account_id: batch.statementType === 'checking' && batch.contextId !== 'unassigned' ? batch.contextId : null, payment_card_id: batch.statementType === 'card' && batch.contextId !== 'unassigned' ? batch.contextId : null, statement_type: batch.statementType, default_currency: batch.defaultCurrency, source_timezone: batch.sourceTimezone, csv_mapping: batch.csvMapping, totals: batch.totals, row_count: batch.rowCount, valid_count: batch.validCount, suspicious_count: batch.suspiciousCount, duplicate_count: batch.duplicateCount, invalid_count: batch.invalidCount, metadata: { encoding: batch.encoding }, created_at: batch.createdAt })
const recordRow = (record, batch) => ({ id: record.id, user_id: batch.userId, import_batch_id: batch.id, source_line: record.sourceLine, raw_payload: record.rawPayload, normalized_payload: { originalCategory: record.originalCategory, notes: record.notes }, original_description: record.originalDescription, normalized_description: record.normalizedDescription, original_amount: record.originalAmount, normalized_amount: record.amount.valid ? record.amount.decimal : null, amount_minor_units: record.amount.valid ? record.amount.minorUnits : null, currency: record.currency, original_date: record.originalDate, source_timezone: record.date.timezone || null, original_instant: record.date.instant || null, accounting_date: record.date.accountingDate || null, external_transaction_id: record.externalTransactionId, fingerprint: record.fingerprint, normalization_version: record.normalizationVersion, inferred_type: record.inferredType, external_status: record.externalStatus, review_status: record.reviewStatus, errors: record.errors, warnings: record.warnings, suspicion_reasons: record.suspicionReasons, possible_duplicate: record.possibleDuplicate })
export const createImportBatchRepository = (client) => ({
  async findDuplicate({ userId, fileHash, statementType, contextId }) { let query = client.from('import_batches').select('*').eq('user_id', userId).eq('file_hash', fileHash).eq('statement_type', statementType).neq('status', 'cancelled'); query = contextId && contextId !== 'unassigned' ? query.eq('financial_account_id', contextId) : query.is('financial_account_id', null); const { data, error } = await query.maybeSingle(); fail(error, 'Localizar reimportação'); return data },
  async savePrepared(batch, records) { if (batch.reprocess) { let query = client.from('import_batches').update({ status: 'cancelled', completed_at: new Date().toISOString() }).eq('user_id', batch.userId).eq('file_hash', batch.fileHash).eq('statement_type', batch.statementType).neq('status', 'cancelled'); query = batch.contextId === 'unassigned' ? query.is('financial_account_id', null).is('payment_card_id', null) : batch.statementType === 'card' ? query.eq('payment_card_id', batch.contextId) : query.eq('financial_account_id', batch.contextId); const cancelled = await query; fail(cancelled.error, 'Preparar reprocessamento') } const saved = await client.from('import_batches').insert(batchRow(batch)).select('*').single(); if (saved.error?.code === '23505') return { duplicate: true }; fail(saved.error, 'Criar lote'); const inserted = await client.from('import_batch_records').insert(records.map((record) => recordRow(record, batch))).select('*'); fail(inserted.error, 'Criar registros do lote'); return { batch: saved.data, records: inserted.data || [] } },
  async listBatches(userId) { const { data, error } = await client.from('import_batches').select('*').eq('user_id', userId).order('created_at', { ascending: false }); fail(error, 'Listar lotes'); return data || [] },
  async listRecords(userId, batchId) { const { data, error } = await client.from('import_batch_records').select('*').eq('user_id', userId).eq('import_batch_id', batchId).order('source_line'); fail(error, 'Listar registros'); return data || [] },
  async decide({ userId, recordId, decision, reviewStatus }) { const { data, error } = await client.from('import_batch_records').update({ user_decision: decision, review_status: reviewStatus, updated_at: new Date().toISOString() }).eq('user_id', userId).eq('id', recordId).select('*').single(); fail(error, 'Salvar decisão'); return data },
  async cancel(userId, batchId) { const { data, error } = await client.from('import_batches').update({ status: 'cancelled', completed_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq('user_id', userId).eq('id', batchId).select('*').single(); fail(error, 'Cancelar lote'); return data },
})
