const fail = (error, action) => { if (error) throw new Error(`${action}: ${error.message}`, { cause: error }) }
export const createOriginRepository = (client) => ({
  async findSource({ userId, sourceType, provider, externalSourceKey }) { let query = client.from('external_sources').select('*').eq('user_id', userId).eq('source_type', sourceType).eq('external_source_key', externalSourceKey); query = provider == null ? query.is('provider', null) : query.eq('provider', provider); const { data, error } = await query.maybeSingle(); fail(error, 'Localizar fonte'); return data },
  async saveSource(row) { const { data, error } = await client.from('external_sources').upsert(row).select('*').single(); fail(error, 'Salvar fonte'); return data },
  async findExternalAccount({ userId, externalSourceId, provider, externalAccountId, fingerprint, fingerprintVersion }) { let query = client.from('external_accounts').select('*').eq('user_id', userId).eq('external_source_id', externalSourceId); if (externalAccountId) { query = query.eq('external_account_id', externalAccountId); query = provider == null ? query.is('provider', null) : query.eq('provider', provider) } else { query = query.eq('account_fingerprint', fingerprint).eq('account_fingerprint_version', fingerprintVersion) } const { data, error } = await query.maybeSingle(); fail(error, 'Localizar conta externa'); return data },
  async saveExternalAccount(row) { const { data, error } = await client.from('external_accounts').upsert(row).select('*').single(); fail(error, 'Salvar conta externa'); return data },
  async findRawIdentity({ userId, externalSourceId, stableExternalKey }) { const { data, error } = await client.from('raw_transactions').select('*').eq('user_id', userId).eq('external_source_id', externalSourceId).eq('stable_external_key', stableExternalKey).maybeSingle(); fail(error, 'Localizar identidade externa'); return data },
  async saveRawIdentity(row) { const { data, error } = await client.from('raw_transactions').upsert(row).select('*').single(); fail(error, 'Salvar identidade externa'); return data },
  async listVersions(userId, rawTransactionId) { const { data, error } = await client.from('raw_transaction_versions').select('*').eq('user_id', userId).eq('raw_transaction_id', rawTransactionId).order('version_number'); fail(error, 'Listar versões'); return data || [] },
  async insertVersion(row) { const { data, error } = await client.from('raw_transaction_versions').insert(row).select('*').single(); if (error?.code === '23505') return null; fail(error, 'Inserir versão imutável'); return data },
  async updateCurrentVersion({ userId, rawTransactionId, versionId, externalStatus, at }) { const { data, error } = await client.from('raw_transactions').update({ current_version_id: versionId, external_status: externalStatus, last_seen_at: at, updated_at: at }).eq('user_id', userId).eq('id', rawTransactionId).select('*').single(); fail(error, 'Atualizar versão corrente'); return data },
})
