export const ORIGIN_SOURCES = Object.freeze(['manual', 'open_finance', 'ofx', 'csv', 'migration', 'system'])
export const EXTERNAL_STATUSES = Object.freeze(['pending', 'posted', 'cancelled', 'removed', 'unknown'])
export const INTERNAL_STATUSES = Object.freeze(['active', 'under_review', 'ignored', 'merged', 'deleted'])
export const RECONCILIATION_STATUSES = Object.freeze(['unmatched', 'suggested', 'matched', 'ignored', 'conflict', 'reverted'])
export const LINK_TYPES = Object.freeze(['identity', 'import', 'sync', 'merge', 'manual_match', 'correction'])
export const ACTOR_TYPES = Object.freeze(['user', 'system', 'provider', 'migration'])
export const DECISIONS = Object.freeze(['match', 'keep_separate', 'ignore', 'merge', 'unmerge', 'restore'])
export const AUDIT_EVENT_TYPES = Object.freeze(['entity_created', 'entity_updated', 'external_version_received', 'external_status_changed', 'link_created', 'merge_completed', 'merge_reverted', 'item_ignored', 'soft_deleted', 'tombstone_created', 'item_reappeared', 'manual_origin_backfilled'])
export const isCanonical = (values, value) => values.includes(value)
