import { useState } from 'react'
import { useFinance } from '../../context/FinanceContext'

const nextCompetence = () => { const date = new Date(); date.setMonth(date.getMonth() + 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}` }
export default function CardSettings({ onClose }) {
  const { cards, addBillingConfiguration, cardBillingMigration, runCardBillingMigration } = useFinance()
  const [selected, setSelected] = useState(cards[0]?.id); const card = cards.find((item) => item.id === selected); const [drafts, setDrafts] = useState(() => Object.fromEntries(cards.map((item) => [item.id, { closingDay: item.closingDay, dueDay: item.dueDay, effectiveFrom: nextCompetence() }]))); const [error, setError] = useState('')
  const set = (field, value) => setDrafts((current) => ({ ...current, [selected]: { ...current[selected], [field]: value } }))
  const submit = (event) => { event.preventDefault(); try { addBillingConfiguration(selected, drafts[selected]); setError(''); onClose() } catch (reason) { setError(reason.message) } }
  return <div className="modal-backdrop"><form className="modal card-settings" role="dialog" aria-modal="true" aria-labelledby="cards-title" onSubmit={submit}><div className="section-heading"><div><p className="eyebrow">Configurações com vigência</p><h2 id="cards-title">Cartões de crédito</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div>{cardBillingMigration < 1 && <div className="settings-feedback info">Converta primeiro as configurações atuais sem alterar faturas.<button type="button" className="outline-button" onClick={runCardBillingMigration}>Criar vigências iniciais</button></div>}<label>Cartão<select value={selected} onChange={(event) => setSelected(event.target.value)}>{cards.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>{card && <><div className="form-grid"><label>Fechamento<input type="number" min="1" max="28" value={drafts[selected].closingDay} onChange={(event) => set('closingDay', event.target.value)} /></label><label>Vencimento<input type="number" min="1" max="28" value={drafts[selected].dueDay} onChange={(event) => set('dueDay', event.target.value)} /></label><label className="span-2">Válida a partir da competência<input type="month" value={drafts[selected].effectiveFrom} onChange={(event) => set('effectiveFrom', event.target.value)} /></label></div><details><summary>Ver histórico</summary>{(card.billingConfigurations || []).map((config) => <p key={config.configId}>{config.effectiveFrom} até {config.effectiveTo || 'atual'} · fecha {config.closingDay} · vence {config.dueDay} · {config.source}</p>)}</details></>}{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="text-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={cardBillingMigration < 1}>Criar nova configuração</button></div></form></div>
}
