import { useEffect, useMemo, useState } from 'react'
import { useAuth } from '../context/AuthContext.jsx'
import { useFinance } from '../context/FinanceContext.jsx'
import { FEATURE_FLAGS, isFeatureEnabled } from '../config/featureFlags.js'
import { prepareImportBatch, decideImportRecord } from '../domain/import/importBatchService.js'
import { createImportBatchRepository } from '../infrastructure/storage/importBatchRepository.js'
import { createAuditRepository } from '../infrastructure/storage/auditRepository.js'
import '../styles/imports.css'

const filters = ['all','new','suspicious','exact_duplicate','possible_duplicate','invalid','accepted','ignored']
const remoteRecord = (row) => ({ id: row.id, sourceLine: row.source_line, rawPayload: row.raw_payload, originalDescription: row.original_description, normalizedDescription: row.normalized_description, originalAmount: row.original_amount, amount: { valid: row.normalized_amount !== null, decimal: row.normalized_amount, minorUnits: row.amount_minor_units }, originalDate: row.original_date, date: { accountingDate: row.accounting_date, timezone: row.source_timezone, instant: row.original_instant }, reviewStatus: row.review_status, errors: row.errors || [], warnings: row.warnings || [], suspicionReasons: row.suspicion_reasons || [], inferredType: row.inferred_type, userDecision: row.user_decision })
export default function ImportsPage() {
  const auth = useAuth(), finance = useFinance(), enabled = isFeatureEnabled(FEATURE_FLAGS.ofxCsvImport)
  const [file, setFile] = useState(null), [options, setOptions] = useState({ statementType: 'checking', contextId: 'unassigned', hasHeader: true, dateFormat: 'br', decimalFormat: 'br', invertSign: false, mapping: null, reprocess: false })
  const [parsed, setParsed] = useState(null), [result, setResult] = useState(null), [error, setError] = useState(null), [filter, setFilter] = useState('all')
  const [history, setHistory] = useState([])
  const repository = useMemo(() => createImportBatchRepository(auth.client), [auth.client]), audit = useMemo(() => createAuditRepository(auth.client), [auth.client])
  useEffect(() => { if (enabled) repository.listBatches(auth.user.id).then(setHistory).catch(() => {}) }, [enabled, repository, auth.user.id])
  const visible = useMemo(() => (result?.records || []).filter((record) => filter === 'all' || record.reviewStatus === filter), [result, filter])
  const persist = async (next) => { const saved = await repository.savePrepared(next.batch, next.records); if (saved.duplicate) { await audit.append({ id: crypto.randomUUID(), user_id: auth.user.id, entity_type: 'import_batch', entity_id: next.batch.id, event_type: 'import_repeated', actor_type: 'user', actor_id: auth.user.id, source: next.batch.fileType, changed_fields: [], metadata: { fileHash: next.batch.fileHash }, idempotency_key: `import:${next.batch.fileHash}:${next.batch.contextId}:repeated`, occurred_at: new Date().toISOString() }); throw new Error('Este arquivo já possui lote neste contexto.') } await audit.append({ id: crypto.randomUUID(), user_id: auth.user.id, entity_type: 'import_batch', entity_id: next.batch.id, event_type: next.batch.reprocess ? 'batch_reprocessed' : 'parsing_completed', actor_type: 'user', actor_id: auth.user.id, source: next.batch.fileType, changed_fields: ['status','counts'], metadata: { fileHash: next.batch.fileHash, rowCount: next.batch.rowCount }, idempotency_key: `import:${next.batch.id}:parsed`, occurred_at: new Date().toISOString() }); setResult(next); setHistory(await repository.listBatches(auth.user.id)) }
  const read = async () => { setError(null); if (!file) return; try { const bytes = new Uint8Array(await file.arrayBuffer()); const next = await prepareImportBatch({ enabled, userId: auth.user.id, file: { name: file.name, bytes }, statementType: options.statementType, csv: options, contextId: options.contextId }); if (!next.success) setError(next.errors?.[0]?.message || 'Arquivo recusado.'); else if (next.requiresMapping) { setParsed(next); setOptions((current) => ({ ...current, mapping: next.parsed.suggestedMapping })) } else await persist(next) } catch (caught) { setError(caught.message) } }
  const processMapped = async () => { if (!file || !options.mapping) return; try { const bytes = new Uint8Array(await file.arrayBuffer()); const next = await prepareImportBatch({ enabled, userId: auth.user.id, file: { name: file.name, bytes }, statementType: options.statementType, csv: options, contextId: options.contextId }); if (next.success) await persist(next); else setError(next.errors?.[0]?.message) } catch (caught) { setError(caught.message) } }
  const decide = async (id, decision) => { try { const current = result.records.find((record) => record.id === id), changed = decideImportRecord(current, decision); await repository.decide({ userId: auth.user.id, recordId: id, decision, reviewStatus: changed.reviewStatus }); await audit.append({ id: crypto.randomUUID(), user_id: auth.user.id, entity_type: 'import_batch_record', entity_id: id, event_type: decision === 'accept' ? 'import_record_accepted' : decision === 'ignore' ? 'import_record_ignored' : 'import_decision_restored', actor_type: 'user', actor_id: auth.user.id, source: result.batch.fileType, changed_fields: ['review_status','user_decision'], metadata: { batchId: result.batch.id }, idempotency_key: `import:${result.batch.id}:${id}:${decision}:${changed.updatedAt}`, occurred_at: changed.updatedAt }); setResult((value) => ({ ...value, records: value.records.map((record) => record.id === id ? changed : record) })) } catch (caught) { setError(caught.message) } }
  const openBatch = async (batch) => { try { const records = await repository.listRecords(auth.user.id, batch.id); setResult({ batch: { id: batch.id, fileType: batch.file_type, originalFilename: batch.original_filename, rowCount: batch.row_count, totals: batch.totals || {} }, records: records.map(remoteRecord) }) } catch (caught) { setError(caught.message) } }
  const cancelBatch = async () => { if (!result?.batch?.id) return; try { await repository.cancel(auth.user.id, result.batch.id); await audit.append({ id: crypto.randomUUID(), user_id: auth.user.id, entity_type: 'import_batch', entity_id: result.batch.id, event_type: 'batch_cancelled', actor_type: 'user', actor_id: auth.user.id, source: result.batch.fileType, changed_fields: ['status'], metadata: {}, idempotency_key: `import:${result.batch.id}:cancelled`, occurred_at: new Date().toISOString() }); setResult(null); setHistory(await repository.listBatches(auth.user.id)) } catch (caught) { setError(caught.message) } }
  if (!enabled) return null
  return <main className="page imports-page"><section className="page-introduction"><div className="page-introduction-copy"><h2>Importar extrato</h2><p>OFX e CSV são preparados para revisão. Nenhum lançamento financeiro é criado nesta etapa.</p></div></section>
    <section className="page-card"><h3>1. Selecionar arquivo</h3><div className="import-controls"><input aria-label="Arquivo OFX ou CSV" type="file" accept=".ofx,.csv" onChange={(event) => { setFile(event.target.files?.[0] || null); setParsed(null); setResult(null) }} /><select aria-label="Natureza do extrato" value={options.statementType} onChange={(event) => setOptions({ ...options, statementType: event.target.value, contextId: 'unassigned' })}><option value="checking">Conta corrente</option><option value="card">Cartão</option></select><select aria-label="Conta ou cartão" value={options.contextId} onChange={(event) => setOptions({ ...options, contextId: event.target.value })}><option value="unassigned">Selecionar depois</option>{(options.statementType === 'card' ? finance.cards : finance.accounts).map((item) => <option key={item.id || item.accountId} value={item.id || item.accountId}>{item.name}</option>)}</select><button type="button" onClick={read} disabled={!file}>Analisar arquivo</button></div>{error && <p role="alert">{error}</p>}</section>
    {parsed && <section className="page-card"><h3>2. Mapear CSV</h3><div className="import-controls"><label>Separador<select value={options.delimiter || parsed.parsed.delimiter} onChange={(event) => setOptions({ ...options, delimiter: event.target.value })}><option value=",">Vírgula</option><option value=";">Ponto e vírgula</option><option value={'\t'}>Tabulação</option></select></label><label>Data<select value={options.dateFormat} onChange={(event) => setOptions({ ...options, dateFormat: event.target.value })}><option value="br">DD/MM/AAAA</option><option value="iso">AAAA-MM-DD</option></select></label><label>Decimal<select value={options.decimalFormat} onChange={(event) => setOptions({ ...options, decimalFormat: event.target.value })}><option value="br">1.234,56</option><option value="international">1,234.56</option><option value="auto">Detectar</option></select></label><label><input type="checkbox" checked={options.hasHeader} onChange={(event) => setOptions({ ...options, hasHeader: event.target.checked })} /> Possui cabeçalho</label></div><div className="import-mapping-grid">{['description','date','amount','debit','credit','currency','externalId','status','notes'].map((field) => <label key={field}>{field}<select value={options.mapping?.[field] ?? ''} onChange={(event) => setOptions({ ...options, mapping: { ...options.mapping, [field]: event.target.value === '' ? undefined : Number(event.target.value) } })}><option value="">Não mapear</option>{parsed.parsed.headers.map((header, index) => <option key={`${header}-${index}`} value={index}>{header}</option>)}</select></label>)}</div><label><input type="checkbox" checked={options.invertSign} onChange={(event) => setOptions({ ...options, invertSign: event.target.checked })} /> Inverter sinais (confirmação explícita)</label><label><input type="checkbox" checked={options.reprocess} onChange={(event) => setOptions({ ...options, reprocess: event.target.checked })} /> Reprocessar explicitamente um lote anterior</label><button type="button" onClick={processMapped}>Processar para revisão</button><div className="import-preview"><strong>Amostra</strong><pre>{JSON.stringify(parsed.preview.slice(0, 5), null, 2)}</pre></div></section>}
    {result && <section className="page-card"><div className="page-card-header"><div><h3>3. Revisar lote</h3><p>Aceitar aprova somente para futura publicação.</p></div><button type="button" onClick={cancelBatch}>Cancelar lote</button></div><div className="import-summary"><span>{result.batch.rowCount} registros</span><span>Entradas {result.batch.totals.income}</span><span>Saídas {result.batch.totals.expense}</span><span>Saldo {result.batch.totals.net}</span></div><div className="import-filters">{filters.map((value) => <button type="button" key={value} className={filter === value ? 'is-active' : ''} onClick={() => setFilter(value)}>{value}</button>)}</div><div className="import-table-wrap"><table><thead><tr><th>Linha</th><th>Descrição</th><th>Data</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>{visible.map((record) => <tr key={record.id}><td>{record.sourceLine}</td><td>{record.originalDescription}<details><summary>Detalhes</summary><pre>{JSON.stringify({ raw: record.rawPayload, normalized: { description: record.normalizedDescription, date: record.date, amount: record.amount }, warnings: record.warnings, errors: record.errors, duplicate: record.possibleDuplicate }, null, 2)}</pre></details></td><td>{record.date.accountingDate || record.originalDate}</td><td>{record.amount.valid ? record.amount.decimal : record.originalAmount}</td><td>{record.reviewStatus}{record.errors.length ? ` — ${record.errors[0].message}` : ''}</td><td><button type="button" disabled={record.reviewStatus === 'invalid'} onClick={() => decide(record.id, 'accept')}>Aceitar</button><button type="button" onClick={() => decide(record.id, 'ignore')}>Ignorar</button><button type="button" onClick={() => decide(record.id, 'restore')}>Restaurar</button></td></tr>)}</tbody></table></div></section>}
    {history.length > 0 && <section className="page-card"><h3>Histórico de lotes</h3><ul>{history.map((batch) => <li key={batch.id}><button type="button" onClick={() => openBatch(batch)}>{batch.original_filename || batch.originalFilename}</button> — {batch.status} — {batch.row_count ?? batch.rowCount} registros</li>)}</ul></section>}
  </main>
}
