import { receiveExternalVersion } from '../origin/externalVersionService.js'
import { classifySyncQuality } from './assistedSync.js'

export const processProviderPage = async ({page,account,run,checkpoint,identities=[],versions=[],adapterVersion='mock-v1'}) => {
  if (checkpoint && page.pageNumber <= checkpoint.pageNumber) return {run,checkpoint,identities,versions,created:[],skipped:page.items.length,errors:[]}
  const byExternal=new Map(identities.map(item=>[item.externalTransactionId,item])),created=[],errors=[];let nextVersions=[...versions],nextIdentities=[...identities],skipped=0
  for(const item of page.items){try{if(!item.externalTransactionId&&!item.providerItemKey)throw new Error('Item sem identidade externa.');const key=item.externalTransactionId||item.providerItemKey;let identity=byExternal.get(key);if(!identity){identity={id:crypto.randomUUID(),userId:run.userId,externalTransactionId:key,externalAccountId:account.id,source:'open_finance',externalStatus:item.externalStatus||'unknown'};byExternal.set(key,identity);nextIdentities.push(identity)}const ownVersions=nextVersions.filter(version=>version.rawTransactionId===identity.id);const received=await receiveExternalVersion({identity,versions:ownVersions,payload:item.payload||item,normalized:item});if(received.created){nextVersions=nextVersions.filter(version=>version.rawTransactionId!==identity.id).concat(received.versions);nextIdentities=nextIdentities.map(current=>current.id===identity.id?received.identity:current);created.push(received.version)}else skipped++}catch(error){errors.push({providerItemKey:item.providerItemKey||null,code:'ITEM_INVALID',message:'Item externo inválido.'})}}
  const processed=(checkpoint?.processedCount||0)+page.items.length
  return {run:{...run,pageNumber:page.pageNumber,cursor:page.nextCursor||null,itemsReceived:(run.itemsReceived||0)+page.items.length,itemsCreated:(run.itemsCreated||0)+created.length,itemsSkipped:(run.itemsSkipped||0)+skipped,itemsFailed:(run.itemsFailed||0)+errors.length,lastCheckpointAt:new Date().toISOString()},checkpoint:{syncRunId:run.id,financialConnectionId:run.financialConnectionId,externalAccountId:account.id,resourceType:'transactions',cursor:page.nextCursor||null,pageNumber:page.pageNumber,lastItemKey:page.items.at(-1)?.externalTransactionId||null,providerCheckpoint:page.checkpoint||null,processedCount:processed,adapterVersion,createdAt:new Date().toISOString()},identities:nextIdentities,versions:nextVersions,created,skipped,errors,hasMore:Boolean(page.hasMore)}
}
export const buildDifferenceReport = ({session,external=[],internal=[],balances=[]}) => {const sum=items=>items.reduce((total,item)=>total+Number(item.amount||0),0),matched=external.filter(item=>item.match?.classification==='exact').length,conflicts=external.filter(item=>item.match?.classification==='conflict').length,pending=external.filter(item=>item.externalStatus==='pending').length,metrics={externalIdCoverage:external.length?external.filter(item=>item.externalTransactionId).length/external.length:0,descriptionCoverage:external.length?external.filter(item=>item.description).length/external.length:0,timezoneCoverage:external.length?external.filter(item=>item.originalTimezone).length/external.length:0,idStability:1,reconciliationRate:external.length?matched/external.length:0};return {assistedSyncSessionId:session.id,status:'generated',periodStart:session.windowStart,periodEnd:session.windowEnd,externalTotals:{amount:sum(external),count:external.length},internalTotals:{amount:sum(internal),count:internal.length},differences:{amount:sum(external)-sum(internal),balanceObservations:balances},unmatchedCount:external.length-matched-conflicts,suggestedCount:external.filter(item=>item.match?.classification==='suggested').length,matchedCount:matched,conflictCount:conflicts,pendingCount:pending,missingExternalCount:Math.max(0,internal.length-matched),missingInternalCount:Math.max(0,external.length-matched),quality:{classification:classifySyncQuality(metrics),metrics},generatedAt:new Date().toISOString()}}
