export const ASSISTED_SYNC_STATUSES = Object.freeze(['draft','awaiting_consent','connecting','discovering_accounts','selecting_accounts','ready','importing','paused','retrying','processing','comparing','awaiting_review','partially_confirmed','confirmed','completed','failed','cancelled'])
export const SAFE_BATCH_CLASSES = Object.freeze(['exact','previously_confirmed','idempotent_reimport'])
export const ASSISTED_SYNC_TRANSITIONS = Object.freeze({draft:['awaiting_consent','cancelled'],awaiting_consent:['connecting','cancelled','failed'],connecting:['discovering_accounts','cancelled','failed'],discovering_accounts:['selecting_accounts','cancelled','failed'],selecting_accounts:['ready','cancelled'],ready:['importing','cancelled'],importing:['paused','retrying','processing','cancelled','failed'],paused:['importing','cancelled'],retrying:['importing','paused','cancelled','failed'],processing:['comparing','cancelled','failed'],comparing:['awaiting_review','failed'],awaiting_review:['partially_confirmed','confirmed','cancelled'],partially_confirmed:['confirmed','cancelled'],confirmed:['completed'],completed:[],failed:['retrying','cancelled'],cancelled:[]})
export const canTransitionAssistedSync = (from, to) => ASSISTED_SYNC_TRANSITIONS[from]?.includes(to) === true
export const transitionAssistedSync = (session, to, at = new Date().toISOString()) => {
  if (!ASSISTED_SYNC_STATUSES.includes(to) || !canTransitionAssistedSync(session.status, to)) { const error = new Error(`Transição inválida: ${session.status} → ${to}.`); error.code = 'INVALID_SYNC_TRANSITION'; error.auditEvent = { eventType:'assisted_sync_transition_rejected', beforeData:{status:session.status}, afterData:{status:to}, occurredAt:at }; throw error }
  return {...session,status:to,currentStep:to,updatedAt:at,...(to==='importing'&&!session.startedAt?{startedAt:at}:{}),...(to==='paused'?{pausedAt:at}:{}),...(session.status==='paused'&&to==='importing'?{resumedAt:at}:{}),...(['completed','failed','cancelled'].includes(to)?{finishedAt:at}:{})}
}
export const createThirtyDayPilot = ({userId,financialConnectionId,provider='mock',environment='sandbox',timezone='America/Sao_Paulo',now=new Date(),scopes=['accounts','balances','transactions']}) => {
  const end = new Date(now); const start = new Date(end); start.setUTCDate(start.getUTCDate()-30)
  return {id:crypto.randomUUID(),userId,financialConnectionId,provider,environment,status:'draft',currentStep:'institution',windowStart:start.toISOString(),windowEnd:end.toISOString(),timezone,selectedAccountIds:[],requestedScopes:scopes,configuration:{pilot:true,reviewRequired:true,automaticPublish:false,historicalExpansion:false},statistics:{received:0,processed:0,skipped:0,failed:0},createdAt:now.toISOString(),updatedAt:now.toISOString()}
}
export const validatePilotWindow = ({windowStart,windowEnd,maxDays=30}) => { const start=new Date(windowStart),end=new Date(windowEnd),days=(end-start)/86400000;if(!Number.isFinite(days)||days<0||days>maxDays){const error=new Error(`A janela inicial deve ter no máximo ${maxDays} dias.`);error.code='UNSAFE_INITIAL_WINDOW';throw error}return true }
export const assertSafeBatch = (items=[]) => { const unsafe=items.filter(item=>!SAFE_BATCH_CLASSES.includes(item.classification)||item.pending||item.conflict||item.multipleCandidates||item.transfer||item.invoicePayment||item.reversal||!item.accountLinked);if(unsafe.length){const error=new Error('O lote contém itens que exigem revisão individual.');error.code='UNSAFE_BATCH';error.excluded=unsafe.map(item=>item.id);throw error}return true }
export const normalizeProviderDate = ({originalTimestamp,originalTimezone=null,accountingDate=null,settlementDate=null,processingDate=null}) => { const parsed=new Date(originalTimestamp);if(Number.isNaN(parsed.valueOf()))throw new TypeError('Timestamp do provider inválido.');return {originalTimestamp,originalTimezone,instantUtc:parsed.toISOString(),localDate:accountingDate||originalTimestamp.slice(0,10),accountingDate:accountingDate||originalTimestamp.slice(0,10),competence:(accountingDate||originalTimestamp.slice(0,10)).slice(0,7),settlementDate,processingDate,timezoneQuality:originalTimezone?'known':'missing'} }
export const classifySyncQuality = (metrics={}) => { const score=(metrics.externalIdCoverage??0)*.25+(metrics.descriptionCoverage??0)*.2+(metrics.timezoneCoverage??0)*.15+(metrics.idStability??0)*.2+(metrics.reconciliationRate??0)*.2;return score>=.85?'good':score>=.65?'acceptable':score>=.4?'partial':score>0?'poor':'unknown' }

