import { useMemo, useState } from 'react'
import { useFinance } from '../../context/FinanceContext'
import { getMonthlyChartSeries, groupTransactionsForChart } from '../../utils/chartSelectors'
import { formatCurrency } from '../../utils/currency'

const colors = ['#713de0', '#9b69ff', '#087759', '#9b5b08', '#c63751', '#286fca', '#687386']; const scopeLabels = { realized: 'Realizado', forecast: 'Previsto', all: 'Realizado + previsto' }
function BarChart({ title, data, scope, id }) { const entries = Object.entries(data).sort((a, b) => b[1].value - a[1].value).slice(0, 7); const max = Math.max(...entries.map(([, item]) => item.value), 1); return <article className="chart-card" aria-labelledby={`${id}-title`} aria-describedby={`${id}-description`}><h3 id={`${id}-title`}>{title}</h3><p id={`${id}-description`} className="visually-hidden">Gráfico de barras em ordem decrescente para o escopo {scopeLabels[scope]}.</p>{entries.length ? <><div className="bar-chart" aria-hidden="true">{entries.map(([label, item], index) => <div className="bar-row" key={label}><div><span>{label}</span><strong>{formatCurrency(item.value)}</strong></div><div className="bar-track"><span style={{ width: `${item.value / max * 100}%`, background: colors[index % colors.length] }} /></div><small>{item.count} lançamento(s)</small></div>)}</div><ul className="visually-hidden">{entries.map(([label, item]) => <li key={label}>{label}: {item.count} lançamentos, {formatCurrency(item.value)}, {scopeLabels[scope]}</li>)}</ul></> : <p className="chart-empty">Não existem lançamentos para este período.</p>}</article> }
function MonthlyChart({ series }) { const max = Math.max(...series.flatMap((item) => [item.expensesRealized, item.expensesForecast]), 1); return <article className="chart-card chart-wide" aria-labelledby="monthly-chart-title" aria-describedby="monthly-chart-description"><h3 id="monthly-chart-title">Evolução mensal de despesas</h3><p id="monthly-chart-description" className="visually-hidden">Comparação mensal entre despesas realizadas e previstas.</p><div className="monthly-bars" aria-hidden="true">{series.map((item) => <div key={item.label} className="monthly-column"><div><i style={{ height: `${item.expensesRealized / max * 100}%` }} /><b style={{ height: `${item.expensesForecast / max * 100}%` }} /></div><span>{item.label}</span></div>)}</div><div className="scope-legend" aria-hidden="true"><span className="realized-dot" />Realizado <span className="forecast-dot" />Previsto</div><ul className="visually-hidden">{series.map((item) => <li key={item.label}>{item.label}: realizado {formatCurrency(item.expensesRealized)}, previsto {formatCurrency(item.expensesForecast)}</li>)}</ul></article> }
export default function Charts() { const { filteredTransactions } = useFinance(); const [scope, setScope] = useState('all'); const charts = useMemo(() => ({ category: groupTransactionsForChart(filteredTransactions, 'category', scope), card: groupTransactionsForChart(filteredTransactions.filter((item) => item.cardId), 'account', scope), necessity: groupTransactionsForChart(filteredTransactions, 'necessity', scope), monthly: getMonthlyChartSeries(filteredTransactions, 6) }), [filteredTransactions, scope]); return <section aria-labelledby="charts-title"><div className="section-heading"><div><p className="eyebrow">Análises</p><h2 id="charts-title">Realizado e previsto</h2></div><div className="scope-selector" role="group" aria-label="Escopo dos gráficos">{Object.entries(scopeLabels).map(([value, label]) => <button type="button" aria-pressed={scope === value} className={scope === value ? 'active' : ''} onClick={() => setScope(value)} key={value}>{label}</button>)}</div></div><div className="charts-grid"><BarChart id="category-chart" title="Despesas por categoria" data={charts.category} scope={scope} /><BarChart id="card-chart" title="Gastos por cartão" data={charts.card} scope={scope} /><BarChart id="necessity-chart" title="Necessidade" data={charts.necessity} scope={scope} /><MonthlyChart series={charts.monthly} /></div></section> }
