import { ACCOUNTING_MATRIX_VERSION } from './eventTypes.js'
const row = (cash, consumption, invoice, result, netWorth, options = {}) => Object.freeze({ cash, consumption, invoice, result, netWorth, requiresLink: false, requiresReview: false, ...options })
export const ACCOUNTING_MATRIX = Object.freeze({
  cash_income: row(1,0,0,1,1), cash_expense: row(-1,1,0,-1,-1), cash_deposit: row(1,0,0,0,0,{requiresReview:true}), cash_withdrawal: row(-1,0,0,0,0,{requiresReview:true}), account_fee: row(-1,1,0,-1,-1), interest_income: row(1,0,0,1,1), interest_charge: row(-1,1,0,-1,-1),
  card_purchase: row(0,1,1,-1,-1,{requiresLink:true}), card_installment: row(0,1,1,-1,-1,{requiresLink:true}), invoice_payment: row(-1,0,-1,0,0,{requiresLink:true}), invoice_partial_payment: row(-1,0,-1,0,0,{requiresLink:true}), invoice_late_payment: row(-1,0,-1,0,0,{requiresLink:true}), invoice_interest: row(-1,1,0,-1,-1,{requiresLink:true}), invoice_fee: row(-1,1,0,-1,-1,{requiresLink:true}), invoice_installment: row(0,0,0,0,0,{requiresLink:true}), invoice_adjustment: row(0,0,-1,0,0,{requiresLink:true,requiresReview:true}),
  internal_transfer_out: row(-1,0,0,0,0,{requiresLink:true}), internal_transfer_in: row(1,0,0,0,0,{requiresLink:true}), external_transfer_out: row(-1,0,0,0,0,{requiresReview:true}), external_transfer_in: row(1,0,0,0,0,{requiresReview:true}), transfer_fee: row(-1,1,0,-1,-1,{requiresLink:true}),
  refund: row(0,-1,-1,1,1,{requiresLink:true}), partial_refund: row(0,-1,-1,1,1,{requiresLink:true}), chargeback: row(0,-1,-1,1,1,{requiresLink:true}), reversal: row(0,0,0,0,0,{requiresLink:true}), voided_transaction: row(0,0,0,0,0,{requiresLink:true}),
  investment_purchase: row(-1,0,0,0,0,{requiresLink:true}), investment_sale: row(1,0,0,0,0,{requiresLink:true}), investment_income: row(1,0,0,1,1), investment_fee: row(-1,0,0,-1,-1,{requiresLink:true}), investment_transfer: row(0,0,0,0,0,{requiresLink:true}), unknown: row(0,0,0,0,0,{requiresReview:true}), under_review: row(0,0,0,0,0,{requiresReview:true}), ignored: row(0,0,0,0,0)
})
export const getAccountingRule = (eventType) => ({ version: ACCOUNTING_MATRIX_VERSION, ...(ACCOUNTING_MATRIX[eventType] || ACCOUNTING_MATRIX.unknown) })
