import { useState } from 'react'
import { useFinance } from '../../context/FinanceContext'
import { isOrphanInvoice } from '../../utils/orphanInvoices'

export default function OrphanInvoicesManager() {
  const { invoicePayments, transactions, cards, archiveOrphanInvoice, restoreArchivedInvoice, permanentlyDeleteArchivedInvoice } = useFinance(); const [confirming, setConfirming] = useState(null); const [phrase, setPhrase] = useState('')
  const records = invoicePayments.map((record) => ({ record, analysis: isOrphanInvoice(record, transactions, cards) })).filter(({ analysis }) => analysis.orphan || analysis.archived)
  return <article className="settings-card"><div className="settings-icon">◇</div><h3>Faturas órfãs e arquivadas</h3><p>Registros vazios são preservados e só mudam mediante ação explícita.</p>{records.length === 0 ? <p className="muted">Nenhum registro candidato.</p> : <div className="record-list">{records.map(({ record, analysis }) => <div className="record-row" key={record.id}><div><strong>{record.id}</strong><span>{analysis.archived ? `Arquivada · ${record.archiveReason}` : `${analysis.reason} · ${analysis.historical ? 'com histórico' : 'sem histórico'}`}</span></div><div>{analysis.archived ? <><button className="text-button" onClick={() => restoreArchivedInvoice(record.id)}>Restaurar</button><button className="text-button" onClick={() => setConfirming(record.id)}>Excluir</button></> : <button className="outline-button" onClick={() => archiveOrphanInvoice(record.id, analysis.reason)}>Arquivar</button>}</div></div>)}</div>}{confirming && <div className="inline-confirm"><p>Digite <strong>EXCLUIR FATURA</strong>. A recuperação exigirá um backup.</p><input value={phrase} onChange={(event) => setPhrase(event.target.value)} /><button className="danger-button" disabled={phrase !== 'EXCLUIR FATURA'} onClick={() => { permanentlyDeleteArchivedInvoice(confirming); setConfirming(null); setPhrase('') }}>Excluir permanentemente</button><button className="text-button" onClick={() => setConfirming(null)}>Cancelar</button></div>}</article>
}
